version: '3.8'

services:
  app:
    image: ${IMAGE_TAG}
    restart: always
    ports:
      - "3000:3000"
    environment:
      NODE_ENV: production
      PORT: "3000"
      HOSTNAME: "0.0.0.0"
      DATABASE_URL: ${DATABASE_URL}