#!/bin/bash
set -e

cd /app

# 1. Load the specific Docker image tag generated by GitHub Actions
if [ -f deploy-env.sh ]; then
  source deploy-env.sh
fi

if [ -z "$IMAGE_TAG" ]; then
  echo "🚨 Error: IMAGE_TAG variable is not set."
  exit 1
fi

# 2. Fetch runtime database credentials securely from AWS SSM Parameter Store
echo "📦 Fetching Application Secrets from AWS SSM..."
DB_URL=$(aws ssm get-parameter \
  --name "/gocart/prod/database_url" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text \
  --region ap-south-1)

if [ -z "$DB_URL" ]; then
  echo "🚨 Error: DATABASE_URL variable fetched from SSM is empty."
  exit 1
fi

# 3. Create the local production environment file
printf "DATABASE_URL=%s\nIMAGE_TAG=%s\n" "$DB_URL" "$IMAGE_TAG" > /app/.env
chmod 600 /app/.env

# 4. Authenticate into GitHub Container Registry using token from SSM
echo "🔑 Logging into GitHub Container Registry..."
GHCR_TOKEN=$(aws ssm get-parameter \
  --name "/github/ghcr/token" \
  --with-decryption \
  --query "Parameter.Value" \
  --output text \
  --region ap-south-1)

echo "$GHCR_TOKEN" | docker login ghcr.io -u lijo-cloud --password-stdin

# 5. Spin up the application container stack
echo "📥 Pulling Docker Image: $IMAGE_TAG"
docker compose pull

echo "🚀 Starting fresh container stack..."
docker compose up -d

# 6. Perform internal container health validation
echo "⏳ Waiting for app container initialization..."
sleep 30

HEALTHY=false
for i in $(seq 1 15); do
  if curl -f http://localhost:3000/api/health >/dev/null 2>&1; then
    HEALTHY=true
    echo "✅ Health check passed successfully"
    break
  fi
  echo "Waiting for app response... attempt $i"
  sleep 5
done

if [ "$HEALTHY" = true ]; then
  echo "✅ Application successfully launched"
  docker image prune -af --filter "until=24h" || true
else
  echo "🚨 Application health check validation failed."
  docker logs $(docker compose ps -q app) --tail 100 || true
  exit 1
fi
